from django.db import models

# Create your models here.
from common.models import AbstractBaseModel
from uam_requests.models import BaseRequest


class ExternalSync(AbstractBaseModel):
    SYNC_AD = 0
    SYNC_NOTES = 1
    SYNC_DEPT_PORTAL = 2
    SYNC_JJO_PORTAL = 3
    # SYNC_SEND_MAIL = 4
    SYNC_TYPES = (
        (SYNC_AD, 'AD'),
        (SYNC_NOTES, 'Lotus Notes'),
        (SYNC_DEPT_PORTAL, 'Departmental Portal'),
        (SYNC_JJO_PORTAL, 'JJO Portal'),
    )
    SYNC_TYPES_DICT = dict(SYNC_TYPES)
    SYNC_ACTION_CREATE_ACCOUNT = 0
    SYNC_ACTION_UPSERT_ACCOUNT = 6
    SYNC_ACTION_DISABLE_ACCOUNT = 1
    SYNC_ACTION_ENABLE_ACCOUNT = 2
    SYNC_ACTION_AMEND_ACCOUNT = 3
    SYNC_ACTION_SEND_MAIL = 4
    SYNC_ACTION_RESET_PASSWORD = 5
    SYNC_ACTIONS = (
        (SYNC_ACTION_CREATE_ACCOUNT, 'Create Account'),
        (SYNC_ACTION_DISABLE_ACCOUNT, 'Disable Account'),
        (SYNC_ACTION_ENABLE_ACCOUNT, 'Enable Account'),
        (SYNC_ACTION_AMEND_ACCOUNT, 'Amend Account'),
        (SYNC_ACTION_SEND_MAIL, 'Send Mail'),
        (SYNC_ACTION_RESET_PASSWORD, 'Reset Password'),
        (SYNC_ACTION_UPSERT_ACCOUNT, 'Create or Amend Account'),
    )
    MAIL_TYPE_CREATE_ACCOUNT_REVIEW = 'CREATE_REVIEW'
    MAIL_TYPE_CREATE_ACCOUNT_EXECUTE = 'CREATE_EXECUTE'
    MAIL_TYPE_CREATE_ACCOUNT_SETUP_COMPLETED = 'CREATE_SETUP_COMPLETED'
    MAIL_TYPE_CREATE_ACCOUNT_USER_ACK = 'USER_ACK'
    MAIL_TYPE_CREATE_ACCOUNT_REJECTED_BY_ITOO = 'CREATE_REJECTED_BY_ITOO'
    MAIL_TYPE_CREATE_ACCOUNT_REJECTED_BY_ITOT = 'CREATE_REJECTED_BY_ITOT'
    MAIL_TYPE_UPDATE_ACCOUNT_REVIEW = 'UPDATE_REVIEW'
    MAIL_TYPE_UPDATE_ACCOUNT_EXECUTE = 'UPDATE_EXECUTE'
    MAIL_TYPE_UPDATE_ACCOUNT_COMPLETED = 'UPDATE_COMPLETED'
    MAIL_TYPE_UPDATE_ACCOUNT_REJECTED_BY_ITOO = 'UPDATE_REJECTED_BY_ITOO'
    MAIL_TYPE_UPDATE_ACCOUNT_REJECTED_BY_ITOT = 'UPDATE_REJECTED_BY_ITOT'
    MAIL_TYPE_DISABLED_ACCOUNT_TO_OWNER = 'DISABLED_ACCOUNT_TO_OWNER'
    MAIL_TYPE_DISABLED_ACCOUNT_TO_EXECUTOR = 'DISABLED_ACCOUNT_TO_EXECUTOR'
    MAIL_TYPE_ENABLED_ACCOUNT_TO_OWNER = 'ENABLED_ACCOUNT_TO_OWNER'
    MAIL_TYPE_ENABLED_ACCOUNT_TO_EXECUTOR = 'ENABLED_ACCOUNT_TO_EXECUTOR'
    MAIL_TYPE_DELETED_ACCOUNT_TO_OWNER = 'DELETED_ACCOUNT_TO_OWNER'
    MAIL_TYPE_DELETED_ACCOUNT_TO_EXECUTOR = 'DELETED_ACCOUNT_TO_EXECUTOR'
    MAIL_TYPE_RESET_PASSWORD_TO_OWNER = 'RESET_PASSWORD_TO_OWNER'
    MAIL_TYPE_RESET_PASSWORD_TO_EXECUTOR = 'RESET_PASSWORD_TO_EXECUTOR'

    SYNC_STATUS_NOT_YET = 0
    SYNC_STATUS_FAILED = 1
    SYNC_STATUS_COMPLETED = 2
    SYNC_STATUS = (
        (SYNC_STATUS_NOT_YET, 'Not Sync'),
        (SYNC_STATUS_FAILED, 'Failed'),
        (SYNC_STATUS_COMPLETED, 'Completed'),
    )
    # MAIL_TYPE_MI = 6
    # MAIL_TYPE_UPDATE_ACCOUNT_USER_ACK = 7

    sync_type = models.IntegerField(choices=SYNC_TYPES)
    sync_action = models.IntegerField(choices=SYNC_ACTIONS, null=True)
    sync_data = models.TextField(null=False, blank=False)
    sync_time = models.DateTimeField(null=True)
    sync_status = models.IntegerField(
        choices=SYNC_STATUS, default=SYNC_STATUS_NOT_YET)
    sync_remarks = models.TextField(null=True)
    request = models.ForeignKey(
        BaseRequest, on_delete=models.SET_NULL, null=True)
