# Generated by Django 2.1.3 on 2019-07-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0002_auto_20190326_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
