# Generated by Django 2.1.3 on 2019-07-08 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetables', '0003_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('business_code', models.SlugField()),
                ('business_description', models.CharField(max_length=200)),
                ('office_code', models.SlugField()),
                ('office_description', models.CharField(max_length=200)),
                ('section_code', models.SlugField()),
                ('section_description', models.CharField(max_length=200)),
                ('code', models.SlugField()),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_section_created', related_query_name='codetables_sections', to=settings.AUTH_USER_MODEL)),
                ('last_modification_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_section_modified', related_query_name='codetables_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
