# Generated by Django 2.1.3 on 2019-07-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0004_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.SlugField(unique=True),
        ),
    ]
