# Generated by Django 2.1.3 on 2019-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0005_auto_20190708_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
    ]
