# Generated by Django 2.1.3 on 2019-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0006_section_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='business_code',
        ),
        migrations.RemoveField(
            model_name='section',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='office_code',
        ),
        migrations.RemoveField(
            model_name='section',
            name='office_description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_code',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_description',
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
