# Generated by Django 2.1.3 on 2019-08-13 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetables', '0009_auto_20190809_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterrank',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='masterrank',
            old_name='modified_date',
            new_name='last_modification_date',
        ),
        migrations.RenameField(
            model_name='substantiverank',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='substantiverank',
            old_name='modified_date',
            new_name='last_modification_date',
        ),
        migrations.RemoveField(
            model_name='masterrank',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='masterrank',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='substantiverank',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='substantiverank',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='masterrank',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_masterrank_created', related_query_name='codetables_masterranks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterrank',
            name='last_modification_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_masterrank_modified', related_query_name='codetables_masterranks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substantiverank',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_substantiverank_created', related_query_name='codetables_substantiveranks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substantiverank',
            name='last_modification_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_substantiverank_modified', related_query_name='codetables_substantiveranks', to=settings.AUTH_USER_MODEL),
        ),
    ]
