# Generated by Django 2.1.3 on 2019-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0010_auto_20190813_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterrank',
            name='value',
            field=models.CharField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
