# Generated by Django 2.1.3 on 2019-08-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0011_auto_20190813_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.RemoveField(
            model_name='substantiverank',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='substantiverank',
            name='last_modification_user',
        ),
        migrations.DeleteModel(
            name='SubstantiveRank',
        ),
    ]
