# Generated by Django 2.1.3 on 2019-08-30 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codetables', '0014_lnaccounttype_lnaddressdomain_lnclientlicense_lnlicensetype_lnmailfileowner_lnmailserver_lnmailsyste'),
    ]

    operations = [
        migrations.CreateModel(
            name='LnMPSRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_lnmpsrange_created', related_query_name='codetables_lnmpsranges', to=settings.AUTH_USER_MODEL)),
                ('last_modification_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codetables_lnmpsrange_modified', related_query_name='codetables_lnmpsranges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lnmpsranges',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='lnmpsranges',
            name='last_modification_user',
        ),
        migrations.DeleteModel(
            name='LnMPSRanges',
        ),
    ]
