# Generated by Django 2.1.2 on 2018-11-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('account_effective_start_date', models.DateField(blank=True, help_text='Account Effective Start Date', null=True)),
                ('account_effective_end_date', models.DateField(blank=True, help_text='Account Effective End Date', null=True)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', help_text='Title', max_length=6)),
                ('surname', models.CharField(blank=True, help_text='Surname', max_length=50, null=True)),
                ('given_name', models.CharField(blank=True, help_text='Given Name', max_length=100, null=True)),
                ('oa_need_windows_login', models.BooleanField(default=False, help_text='Required Windows Account?')),
                ('oa_need_lotus_notes', models.BooleanField(default=False, help_text='Required Notes Account?')),
                ('account_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Disabled'), (2, 'Deleted')], default=0, help_text='Account Status')),
                ('ad_windows_login_name', models.CharField(blank=True, help_text='Windows Account Login Name', max_length=255, null=True)),
                ('ad_account_expiry_date', models.DateTimeField(blank=True, help_text='Windows Account Expiry Date', null=True)),
                ('ad_need_change_password_next_login', models.BooleanField(default=True, help_text='User needs to change password at next login?')),
                ('ad_windows_login_password', models.CharField(blank=True, help_text='Windows Account Login Password', max_length=255, null=True)),
                ('ln_lotus_notes_mail_name', models.CharField(blank=True, help_text='Notes Account Mail Name', max_length=50, null=True)),
                ('ln_short_name', models.CharField(blank=True, help_text='Notes Account Short Name', max_length=50, null=True)),
                ('ln_notes_display_name', models.CharField(blank=True, help_text='Notes Account Display Name', max_length=50, null=True)),
                ('ln_notes_account', models.CharField(blank=True, help_text='Notes Account Name', max_length=50, null=True)),
                ('ln_notes_password', models.CharField(blank=True, help_text='Notes Password', max_length=50, null=True)),
                ('uam_id', models.CharField(max_length=100, unique=True)),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uam_users_uamuser_created', related_query_name='uam_users_uamusers', to=settings.AUTH_USER_MODEL)),
                ('last_modification_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uam_users_uamuser_modified', related_query_name='uam_users_uamusers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
