# Generated by Django 2.1.2 on 2018-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='uam_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
