# Generated by Django 2.1.2 on 2018-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0002_auto_20181106_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ad_sync_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='notes_sync_time',
            field=models.DateTimeField(null=True),
        ),
    ]
