# Generated by Django 2.1.3 on 2019-01-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0003_auto_20181107_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
