# Generated by Django 2.1.3 on 2019-01-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0005_uamuser_ad_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='post_title',
            field=models.CharField(blank=True, help_text='Post Title', max_length=100, null=True),
        ),
    ]
