# Generated by Django 2.1.3 on 2019-03-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0006_uamuser_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='title',
            field=models.CharField(blank=True, help_text='Title', max_length=6, null=True),
        ),
    ]
