# Generated by Django 2.1.3 on 2019-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0007_auto_20190305_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='uam_id',
            field=models.IntegerField(unique=True),
        ),
    ]
