# Generated by Django 2.1.3 on 2019-07-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0008_auto_20190709_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='uam_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
