# Generated by Django 2.1.3 on 2019-07-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0007_auto_20190711_1721'),
        ('uam_users', '0009_auto_20190710_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='codetables.Section', to_field='code'),
        ),
    ]
