# Generated by Django 2.1.3 on 2019-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0011_uamuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'JJO'), (2, 'Non-JJO'), (3, 'Special Account')], default=2, help_text='Account type'),
        ),
    ]
