# Generated by Django 2.1.3 on 2019-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0008_adgroup'),
        ('uam_users', '0012_auto_20190803_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ad_user_groups',
            field=models.ManyToManyField(to='codetables.AdGroup'),
        ),
    ]
