# Generated by Django 2.1.3 on 2019-08-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0013_uamuser_ad_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uamuser',
            name='ad_groups',
        ),
    ]
