# Generated by Django 2.1.3 on 2019-08-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0009_auto_20190809_1815'),
        ('uam_users', '0014_remove_uamuser_ad_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ln_user_groups',
            field=models.ManyToManyField(to='codetables.LnGroup'),
        ),
    ]
