# Generated by Django 2.1.3 on 2019-08-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0010_auto_20190813_1145'),
        ('uam_users', '0015_uamuser_ln_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='master_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_ranked_user', to='codetables.MasterRank'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='substantive_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substantive_ranked_user', to='codetables.MasterRank'),
        ),
    ]
