# Generated by Django 2.1.3 on 2019-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0016_auto_20190813_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='given_name_chinese',
            field=models.CharField(blank=True, help_text='Given Name (Chinese)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='surname_chinese',
            field=models.CharField(blank=True, help_text='Surname (Chinese)', max_length=50, null=True),
        ),
    ]
