# Generated by Django 2.1.3 on 2019-08-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0013_auto_20190829_1902'),
        ('uam_users', '0018_uamuser_prefered_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ad_ou',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ad_ou_user', to='codetables.ActiveDirectoryOU'),
        ),
    ]
