# Generated by Django 2.1.3 on 2019-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0021_auto_20190830_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uamuser',
            name='_ad_ps_magistrate_of_lt',
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ad_ps_magistrate_of_lt',
            field=models.CharField(blank=True, help_text='PS of Magistrate/Presiding Officer of Labour Tribunal', max_length=255, null=True),
        ),
    ]
