# Generated by Django 2.1.3 on 2019-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0022_auto_20190830_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uamuser',
            name='ad_ps_magistrate_of_lt',
            field=models.CharField(blank=True, help_text='PS of Magistrate/Presiding Officer of Labour Tribunal', max_length=1000, null=True),
        ),
    ]
