# Generated by Django 2.1.3 on 2019-08-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0024_auto_20190830_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ln_is_confidential_mail_user',
            field=models.BooleanField(default=False, help_text='Confidential Mail User?'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_is_gcn_user',
            field=models.BooleanField(default=False, help_text='GCN User?'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_is_inote_user',
            field=models.BooleanField(default=False, help_text='iNote User?'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_is_internet_mail_user',
            field=models.BooleanField(default=False, help_text='Internet Mail User?'),
        ),
    ]
