# Generated by Django 2.1.3 on 2019-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0025_auto_20190830_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ln_is_contractor',
            field=models.BooleanField(default=False, help_text='Contractor?'),
        ),
    ]
