# Generated by Django 2.1.3 on 2019-08-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0015_auto_20190830_1956'),
        ('uam_users', '0026_uamuser_ln_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ln_account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_account_type_user', to='codetables.LnAccountType'),
        ),
    ]
