# Generated by Django 2.1.3 on 2019-09-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0015_auto_20190830_1956'),
        ('uam_users', '0029_auto_20190901_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='ln_database_quota',
            field=models.IntegerField(help_text='Database Quota (MB)', null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_internet_address',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_mail_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_mail_domain_user', to='codetables.LnAddressDomain'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_mail_file_name',
            field=models.CharField(blank=True, help_text='Mail File Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_set_database_quota',
            field=models.BooleanField(default=False, help_text='Set Database Quota?'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_set_warning_threshold',
            field=models.BooleanField(default=False, help_text='Set Warning Threshold?'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='ln_warning_threshold',
            field=models.IntegerField(help_text='Warning Threshold (MB)', null=True),
        ),
    ]
