# Generated by Django 2.1.3 on 2019-09-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0015_auto_20190830_1956'),
        ('uam_users', '0030_auto_20190901_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='jjo_email',
            field=models.SlugField(help_text='JJO Portal email address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='jjo_first_name',
            field=models.CharField(blank=True, help_text='JJO Portal First Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='jjo_last_name',
            field=models.CharField(blank=True, help_text='JJO Portal Last Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='jjo_login_id',
            field=models.CharField(blank=True, help_text='JJ Portal Login ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='jjo_mail_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jjo_mail_domain_user', to='codetables.LnAddressDomain'),
        ),
    ]
