# Generated by Django 2.1.3 on 2019-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0031_auto_20190903_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='oa_need_jjo',
            field=models.BooleanField(default=False, help_text='Required JJO Portal Account?'),
        ),
    ]
