# Generated by Django 2.1.3 on 2019-09-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0017_dpemployeetype_dprankcode_dpstaffgroup'),
        ('uam_users', '0032_uamuser_oa_need_jjo'),
    ]

    operations = [
        migrations.AddField(
            model_name='uamuser',
            name='dp_dep_id',
            field=models.CharField(blank=True, help_text='Department ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_emp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dp_emp_type_user', to='codetables.DpEmployeeType'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_first_name',
            field=models.CharField(blank=True, help_text='DP First Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_hkid',
            field=models.SlugField(blank=True, help_text='HKID (First 4 letters)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_last_name',
            field=models.CharField(blank=True, help_text='DP Last Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_login_id',
            field=models.CharField(blank=True, help_text='DP Login ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_net_mail',
            field=models.CharField(blank=True, help_text='Net Mail Address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_rank_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dp_rank_code_user', to='codetables.DpRankCode'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_roma_full_name',
            field=models.CharField(blank=True, help_text='ROMA Full Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_roma_id',
            field=models.SlugField(blank=True, help_text='ROMA ID', null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_staff_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dp_staff_code_user', to='codetables.DpStaffGroup'),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='dp_uid_saml',
            field=models.CharField(blank=True, help_text='Unique ID for SAML', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uamuser',
            name='oa_need_dp',
            field=models.BooleanField(default=False, help_text='Required Departmental Portal Account?'),
        ),
    ]
