# Generated by Django 2.1.3 on 2019-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_users', '0033_auto_20190904_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uamuser',
            old_name='ad_ps_magistrate_of_lt',
            new_name='_ad_ps_magistrate_of_lt',
        ),
        migrations.AlterField(
            model_name='uamuser',
            name='_ad_ps_magistrate_of_lt',
            field=models.CharField(blank=True, db_column='ad_ps_magistrate_of_lt', help_text='PS of Magistrate/Presiding Officer of Labour Tribunal', max_length=1000, null=True),
        ),
    ]
