# Generated by Django 2.1.2 on 2018-11-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uam_users', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_log_data', models.TextField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'New Request'), (1, 'Pending for review'), (2, 'Reviewed by ITOO'), (3, 'Confirmed by HelpDesk'), (4, 'Rejected by ITOO'), (5, 'Rejected by ITOT'), (6, 'Completed')], default=0)),
                ('request_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.BaseRequest')),
                ('account_effective_start_date', models.DateField(blank=True, help_text='Account Effective Start Date', null=True)),
                ('account_effective_end_date', models.DateField(blank=True, help_text='Account Effective End Date', null=True)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.')], default='Mr.', help_text='Title', max_length=6)),
                ('surname', models.CharField(blank=True, help_text='Surname', max_length=50, null=True)),
                ('given_name', models.CharField(blank=True, help_text='Given Name', max_length=100, null=True)),
                ('oa_need_windows_login', models.BooleanField(default=False, help_text='Required Windows Account?')),
                ('oa_need_lotus_notes', models.BooleanField(default=False, help_text='Required Notes Account?')),
                ('account_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Disabled'), (2, 'Deleted')], default=0, help_text='Account Status')),
                ('ad_windows_login_name', models.CharField(blank=True, help_text='Windows Account Login Name', max_length=255, null=True)),
                ('ad_account_expiry_date', models.DateTimeField(blank=True, help_text='Windows Account Expiry Date', null=True)),
                ('ad_need_change_password_next_login', models.BooleanField(default=True, help_text='User needs to change password at next login?')),
                ('ad_windows_login_password', models.CharField(blank=True, help_text='Windows Account Login Password', max_length=255, null=True)),
                ('ln_lotus_notes_mail_name', models.CharField(blank=True, help_text='Notes Account Mail Name', max_length=50, null=True)),
                ('ln_short_name', models.CharField(blank=True, help_text='Notes Account Short Name', max_length=50, null=True)),
                ('ln_notes_display_name', models.CharField(blank=True, help_text='Notes Account Display Name', max_length=50, null=True)),
                ('ln_notes_account', models.CharField(blank=True, help_text='Notes Account Name', max_length=50, null=True)),
                ('ln_notes_password', models.CharField(blank=True, help_text='Notes Password', max_length=50, null=True)),
                ('oth_other_request', models.TextField(blank=True, help_text='Other Requests', null=True)),
                ('oth_other_justification', models.TextField(blank=True, help_text='Other Justifications', null=True)),
                ('oth_other_remark', models.TextField(blank=True, help_text='Other Remarks', null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.baserequest', models.Model),
        ),
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.BaseRequest')),
                ('new_password', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.baserequest',),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uam_requests_baserequest_created', related_query_name='uam_requests_baserequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='last_modification_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uam_requests_baserequest_modified', related_query_name='uam_requests_baserequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_uam_requests.baserequest_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='related_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='requests', to='uam_users.UamUser'),
        ),
        migrations.CreateModel(
            name='CreateAccountRequest',
            fields=[
                ('accountrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.AccountRequest')),
                ('installation_contact_person', models.CharField(blank=True, help_text='Installation Contact Person', max_length=50, null=True)),
                ('installation_contact_phone_no', models.CharField(blank=True, help_text='Installation Contact Tel.', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.accountrequest',),
        ),
        migrations.CreateModel(
            name='UpdateAccountRequest',
            fields=[
                ('accountrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.AccountRequest')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.accountrequest',),
        ),
    ]
