# Generated by Django 2.1.2 on 2018-11-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserequest',
            name='request_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
