# Generated by Django 2.1.3 on 2019-01-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0003_auto_20190121_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='ad_groups',
            field=models.CharField(blank=True, help_text='Windows AD Groups', max_length=255, null=True),
        ),
    ]
