# Generated by Django 2.1.3 on 2019-03-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0005_accountrequest_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisableAccountRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.BaseRequest')),
                ('uam_ids', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.baserequest',),
        ),
        migrations.AddField(
            model_name='updateaccountrequest',
            name='uam_id',
            field=models.CharField(blank=True, help_text='UAM ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Title', max_length=6, null=True),
        ),
    ]
