# Generated by Django 2.1.3 on 2019-03-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0006_auto_20190305_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='uam_ids',
        ),
    ]
