# Generated by Django 2.1.3 on 2019-03-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0007_remove_disableaccountrequest_uam_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='disableaccountrequest',
            name='user_ids',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
