# Generated by Django 2.1.3 on 2019-03-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0008_disableaccountrequest_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccountRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.BaseRequest')),
                ('user_ids', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.baserequest',),
        ),
        migrations.CreateModel(
            name='EnableAccountRequest',
            fields=[
                ('baserequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='uam_requests.BaseRequest')),
                ('user_ids', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('uam_requests.baserequest',),
        ),
    ]
