# Generated by Django 2.1.3 on 2019-03-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0009_deleteaccountrequest_enableaccountrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disableaccountrequest',
            old_name='user_ids',
            new_name='user_id',
        ),
    ]
