# Generated by Django 2.1.3 on 2019-03-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0010_auto_20190307_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deleteaccountrequest',
            old_name='user_ids',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='enableaccountrequest',
            old_name='user_ids',
            new_name='user_id',
        ),
    ]
