# Generated by Django 2.1.3 on 2019-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0011_auto_20190307_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='disableaccountrequest',
            name='account_effective_end_date',
            field=models.DateField(blank=True, help_text='Account Effective End Date', null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='account_effective_start_date',
            field=models.DateField(blank=True, help_text='Account Effective Start Date', null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='account_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Disabled'), (2, 'Deleted')], default=0, help_text='Account Status'),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ad_account_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Windows Account Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ad_groups',
            field=models.CharField(blank=True, help_text='Windows AD Groups', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ad_need_change_password_next_login',
            field=models.BooleanField(default=True, help_text='User needs to change password at next login?'),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ad_windows_login_name',
            field=models.CharField(blank=True, help_text='Windows Account Login Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ad_windows_login_password',
            field=models.CharField(blank=True, help_text='Windows Account Login Password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='given_name',
            field=models.CharField(blank=True, help_text='Given Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ln_lotus_notes_mail_name',
            field=models.CharField(blank=True, help_text='Notes Account Mail Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ln_notes_account',
            field=models.CharField(blank=True, help_text='Notes Account Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ln_notes_display_name',
            field=models.CharField(blank=True, help_text='Notes Account Display Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ln_notes_password',
            field=models.CharField(blank=True, help_text='Notes Password', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='ln_short_name',
            field=models.CharField(blank=True, help_text='Notes Account Short Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='oa_need_lotus_notes',
            field=models.BooleanField(default=False, help_text='Required Notes Account?'),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='oa_need_windows_login',
            field=models.BooleanField(default=False, help_text='Required Windows Account?'),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='post_title',
            field=models.CharField(blank=True, help_text='Post Title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='surname',
            field=models.CharField(blank=True, help_text='Surname', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disableaccountrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Title', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='baserequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'New Request'), (1, 'Pending by ITOO'), (2, 'Pending by ITOO'), (3, 'Confirmed by HelpDesk'), (4, 'Rejected by ITOO'), (5, 'Rejected by ITOT'), (6, 'Setup Completed'), (7, 'User Acknowledge'), (8, 'Reset Password Completed'), (9, 'Disable Completed'), (10, 'Enable Completed'), (11, 'Delete Completed')], default=0),
        ),
    ]
