# Generated by Django 2.1.3 on 2019-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0012_auto_20190310_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='account_effective_end_date',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='account_effective_start_date',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ad_account_expiry_date',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ad_groups',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ad_need_change_password_next_login',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ad_windows_login_name',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ad_windows_login_password',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='given_name',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ln_lotus_notes_mail_name',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ln_notes_account',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ln_notes_display_name',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ln_notes_password',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='ln_short_name',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='oa_need_lotus_notes',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='oa_need_windows_login',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='disableaccountrequest',
            name='title',
        ),
    ]
