# Generated by Django 2.1.3 on 2019-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0014_auto_20190325_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baserequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, "Pending For ITOO's review"), (2, "Pending For ITOT's review"), (3, 'Confirmed by HelpDesk'), (4, 'Rejected by ITOO'), (5, 'Rejected by ITOT'), (6, 'Setup Completed'), (7, 'User Acknowledge'), (8, 'Reset Password Completed'), (9, 'Disable Account Completed'), (10, 'Re-Enable Account Completed'), (11, 'Delete Account Completed'), (12, 'Update Account Completed')], default=0),
        ),
    ]
