# Generated by Django 2.1.3 on 2019-04-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0016_auto_20190409_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateaccountrequest',
            name='changes',
        ),
    ]
