# Generated by Django 2.1.3 on 2019-04-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0017_remove_updateaccountrequest_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateaccountrequest',
            name='value_changes',
            field=models.CharField(blank=True, help_text='Changes', max_length=1000, null=True),
        ),
    ]
