# Generated by Django 2.1.3 on 2019-04-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0018_updateaccountrequest_value_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateaccountrequest',
            name='value_changes',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
