# Generated by Django 2.1.3 on 2019-04-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0019_auto_20190410_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateaccountrequest',
            name='value_changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
