# Generated by Django 2.1.3 on 2019-05-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0020_auto_20190410_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMailTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=2000)),
                ('cc', models.CharField(max_length=2000, null=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, "Pending For ITOO's review"), (2, "Pending For ITOT's review"), (3, 'Confirmed by HelpDesk'), (4, 'Rejected by ITOO'), (5, 'Rejected by ITOT'), (6, 'Setup Completed'), (7, 'User Acknowledged'), (8, 'Reset Password Completed'), (9, 'Disable Account Completed'), (10, 'Re-Enable Account Completed'), (11, 'Delete Account Completed'), (12, 'Update Account Completed')])),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uam_requests.BaseRequest')),
            ],
        ),
    ]
