# Generated by Django 2.1.3 on 2019-05-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0021_requestmailto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestmailto',
            unique_together={('request', 'status')},
        ),
    ]
