# Generated by Django 2.1.3 on 2019-05-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0022_auto_20190524_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmailto',
            name='to',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
