# Generated by Django 2.1.3 on 2019-05-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0023_auto_20190524_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmailto',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_mail_to', to='uam_requests.BaseRequest'),
        ),
    ]
