# Generated by Django 2.1.3 on 2019-05-27 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0024_auto_20190524_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmailto',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_to', to='uam_requests.BaseRequest'),
        ),
    ]
