# Generated by Django 2.1.3 on 2019-06-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0025_auto_20190527_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmailto',
            old_name='cc',
            new_name='_cc',
        ),
        migrations.RenameField(
            model_name='requestmailto',
            old_name='to',
            new_name='_to',
        ),
        migrations.AlterField(
            model_name='requestmailto',
            name='_cc',
            field=models.CharField(db_column='cc', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='requestmailto',
            name='_to',
            field=models.CharField(db_column='to', max_length=2000, null=True),
        ),
    ]
