# Generated by Django 2.1.3 on 2019-06-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0027_auto_20190603_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='file_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requestfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
