# Generated by Django 2.1.3 on 2019-06-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0028_auto_20190610_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdamPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_submit_create_request', 'Can prepare and submit account creation request'), ('can_review_create_request', 'Can review and reject account creation request'), ('can_execute_create_request', 'Can execute and reject account creation request'), ('can_view_create_request', 'Can view account creation request'), ('can_submit_update_request', 'Can prepare and submit account update request'), ('can_review_update_request', 'Can review and reject account update request'), ('can_execute_update_request', 'Can execute and reject account update request'), ('can_view_update_request', 'Can view account update request')),
                'managed': False,
            },
        ),
    ]
