# Generated by Django 2.1.3 on 2019-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0032_auto_20190709_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baserequest',
            options={},
        ),
        migrations.AddField(
            model_name='baserequest',
            name='query_given_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='query_post_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='query_request_type_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='query_status_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baserequest',
            name='query_surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['query_status_desc'], name='uam_request_query_s_85b5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['query_request_type_desc'], name='uam_request_query_r_0042a4_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['query_given_name'], name='uam_request_query_g_706fae_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['query_surname'], name='uam_request_query_s_172702_idx'),
        ),
        migrations.AddIndex(
            model_name='baserequest',
            index=models.Index(fields=['query_post_title'], name='uam_request_query_p_27085a_idx'),
        ),
    ]
