# Generated by Django 2.1.3 on 2019-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0034_baserequest_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='sync_time',
            field=models.DateTimeField(null=True),
        ),
    ]
