# Generated by Django 2.1.3 on 2019-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0035_auditlog_sync_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'JJO'), (0, 'Non-JJO'), (2, 'Special Account')], default=0, help_text='Account type'),
        ),
    ]
