# Generated by Django 2.1.3 on 2019-08-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0010_auto_20190813_1145'),
        ('uam_requests', '0041_auto_20190813_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='master_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_ranked_request', to='codetables.MasterRank'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='substantive_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substantive_ranked_request', to='codetables.MasterRank'),
        ),
    ]
