# Generated by Django 2.1.3 on 2019-08-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0043_auto_20190829_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='prefered_name',
            field=models.CharField(blank=True, help_text='Prefered Name', max_length=100, null=True),
        ),
    ]
