# Generated by Django 2.1.3 on 2019-08-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0045_accountrequest_ad_ou'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='ad_is_magistrate_of_lt',
            field=models.BooleanField(default=False, help_text='Magistrate/Presiding Officer of Labour Tribunal'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ad_ps_magistrate_of_lt',
            field=models.CharField(blank=True, help_text='PS of Magistrate/Presiding Officer of Labour Tribunal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ad_windows_first_name',
            field=models.CharField(blank=True, help_text='Windows First Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ad_windows_last_name',
            field=models.CharField(blank=True, help_text='Windows Last Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='ad_account_expiry_date',
            field=models.DateField(blank=True, help_text='Windows Account Expiry Date', null=True),
        ),
    ]
