# Generated by Django 2.1.3 on 2019-08-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0046_auto_20190830_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrequest',
            old_name='ad_ps_magistrate_of_lt',
            new_name='_ad_ps_magistrate_of_lt',
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='_ad_ps_magistrate_of_lt',
            field=models.CharField(blank=True, db_column='ad_ps_magistrate_of_lt', help_text='PS of Magistrate/Presiding Officer of Labour Tribunal', max_length=255, null=True),
        ),
    ]
