# Generated by Django 2.1.3 on 2019-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0049_auto_20190830_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='ln_first_name',
            field=models.CharField(blank=True, help_text='Notes Account First Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_last_name',
            field=models.CharField(blank=True, help_text='Notes Account Last Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_middle_name',
            field=models.CharField(blank=True, help_text='Notes Account Middle Name', max_length=50, null=True),
        ),
    ]
