# Generated by Django 2.1.3 on 2019-09-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0015_auto_20190830_1956'),
        ('uam_requests', '0054_accountrequest_ln_client_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='ln_license_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_license_type_request', to='codetables.LnLicenseType'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_mail_file_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_mail_file_owner_request', to='codetables.LnMailFileOwner'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_mail_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_mail_server_request', to='codetables.LnMailServer'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_mail_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_mail_system_request', to='codetables.LnMailSystem'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_mail_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_mail_template_request', to='codetables.LnMailTemplate'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='ln_mps_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ln_mps_range_request', to='codetables.LnMPSRange'),
        ),
    ]
