# Generated by Django 2.1.3 on 2019-09-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0059_auto_20190904_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idampermissions',
            options={'managed': False, 'permissions': (('can_submit_create_request', 'Can prepare and submit account creation request'), ('can_review_create_request', 'Can review and reject account creation request'), ('can_execute_create_request', 'Can execute and reject account creation request'), ('can_enquire_request', 'Can enquire requests'), ('can_submit_update_request', 'Can prepare and submit account update request'), ('can_review_update_request', 'Can review and reject account update request'), ('can_execute_update_request', 'Can execute and reject account update request'), ('can_enquire_account', 'Can enquire UAM accounts'), ('can_disable_account', 'Can disable UAM accounts'), ('can_delete_account', 'Can delete UAM accounts'), ('can_reset_password', 'Can Reset Password'), ('can_enable_account', 'Can enable account'), ('can_manage_all_sections', 'Can Manage user information for all sections'), ('can_complete_create_request', 'Can Complete Setup account creation request'))},
        ),
    ]
