# Generated by Django 2.1.3 on 2019-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uam_requests', '0060_auto_20190906_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateaccountrequest',
            old_name='value_changes',
            new_name='_value_changes',
        ),
        migrations.AlterField(
            model_name='updateaccountrequest',
            name='_value_changes',
            field=models.TextField(blank=True, db_column='value_changes', null=True),
        ),
    ]
