# Generated by Django 2.1.3 on 2019-09-30 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetables', '0017_dpemployeetype_dprankcode_dpstaffgroup'),
        ('uam_requests', '0062_auto_20190918_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='jjo_emp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jjo_emp_type_request', to='codetables.DpEmployeeType'),
        ),
    ]
