# Generated by Django 2.1.3 on 2019-08-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uam_requests', '0034_baserequest_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('sync_type', models.IntegerField(choices=[(0, 'AD'), (1, 'Lotus Notes'), (2, 'Departmental Portal'), (3, 'JJO Portal')])),
                ('sync_data', models.TextField()),
                ('sync_time', models.DateTimeField(null=True)),
                ('creation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interface_externalsync_created', related_query_name='interface_externalsyncs', to=settings.AUTH_USER_MODEL)),
                ('last_modification_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interface_externalsync_modified', related_query_name='interface_externalsyncs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uam_requests.BaseRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
