# Generated by Django 2.1.3 on 2019-09-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20190829_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsync',
            name='sync_action',
            field=models.IntegerField(choices=[(0, 'Create Account'), (1, 'Disable Account'), (2, 'Enable Account'), (3, 'Amend Account'), (4, 'Send Mail')], null=True),
        ),
        migrations.AlterField(
            model_name='externalsync',
            name='sync_type',
            field=models.IntegerField(choices=[(0, 'AD'), (1, 'Lotus Notes'), (2, 'Departmental Portal'), (3, 'JJO Portal')]),
        ),
    ]
