# Generated by Django 2.1.3 on 2019-09-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20190920_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsync',
            name='sync_action',
            field=models.IntegerField(choices=[(0, 'Create Account'), (1, 'Disable Account'), (2, 'Enable Account'), (3, 'Amend Account'), (4, 'Send Mail'), (5, 'Reset Password')], null=True),
        ),
    ]
