# Generated by Django 2.1.3 on 2019-09-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20190923_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsync',
            name='sync_remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='externalsync',
            name='sync_status',
            field=models.IntegerField(choices=[(0, 'Not Sync'), (1, 'Failed'), (2, 'Completed')], default=0),
        ),
    ]
