# Generated by Django 2.1.3 on 2019-10-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20190930_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsync',
            name='sync_action',
            field=models.IntegerField(choices=[(0, 'Create Account'), (1, 'Disable Account'), (2, 'Enable Account'), (3, 'Amend Account'), (4, 'Send Mail'), (5, 'Reset Password'), (6, 'Create or Amend Account')], null=True),
        ),
    ]
