"""
Django settings for uam2 project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
# import posixpath
# from django.utils.timezone import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9jf8x$)g6on@tcl@64um*+_lj(a+a57%(*yfp+(7z)!97cvt^-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'rest_framework',
    'polymorphic',
    'uam_users',
    'uam_requests',
    'interface',
    'codetables',
    'corsheaders',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'spa.middleware.SPAMiddleware',
]

ROOT_URLCONF = 'uam2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uam2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'HOST': "172.18.21.166",
        'USER': "uam_user",
        'PASSWORD': "P@ssIDAM",
        'NAME': "uam_new",
        'PORT': 1433,
        'OPTIONS': {
            # 'driver': 'SQL Server Native Client 11.0',
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }

}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# if DEBUG:
#     import logging
#     l = logging.getLogger('django.db.backends')
#     l.setLevel(logging.DEBUG)
#     l.addHandler(logging.StreamHandler())

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] [%(levelname)s] %(message)s '
        },
    },
    'handlers': {
        'console': {
            # 'level': 'INFO',
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        # 'file': {
        #	'level': 'INFO',
        #	'class': 'logging.FileHandler',
        #	'filename': os.path.join('log/', 'log_' + datetime.today().strftime('%Y%m%d') +  '.txt'),
        #	'formatter': 'verbose'
        # },
        # 'email': {
        #	'level': 'ERROR',
        #	'class': 'django.utils.log.AdminEmailHandler',
        #	'include_html': True,
        # }
    },
    'loggers': {
        'uam_requests': {
            'handlers': ['console'],
            'level': 'DEBUG',
            # 'level': 'INFO',
        },
        'django.db.backends': {
            'handlers': ['console'],
            # 'level': 'DEBUG',
            'level': 'INFO',
        },
        'common': {
            'handlers': ['console'],
            'level': 'INFO',
            # 'level': 'DEBUG',
        },
        # 'django': {
        # 	#'handlers': ['console', 'file', 'email'],
        #     'handlers': ['console'],
        # 	'level': 'INFO',
        # 	'propagate': True,
        # },
    },
}


REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'common.jud_auth.JudAuthentication',
    ],
    'DATE_FORMAT': "%d/%m/%Y",
    "DATE_INPUT_FORMATS": ["%d/%m/%Y"],
    "DATETIME_FORMAT": "%d/%m/%Y %H:%M:%S",
    "DATETIME_INPUT_FORMATS": ["%d/%m/%Y %H:%M:%S"],
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
}

CORS_ORIGIN_ALLOW_ALL = True

AMQP_URI = 'pyamqp://linuxadmin:P@ssw0rd@172.18.21.116'
AMQP_SSL = False
# NAMEKO_CONFIG = {
#     'AMQP_URI' : 'pyamqp://linuxadmin:P@ssw0rd@172.18.21.116'
# }

# To expire session in predefined period of inactivity
SESSION_COOKIE_AGE = 1800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

MEDIA_URL = 'temp/'
# MEDIA_ROOT = os.path.join('D:/pythontools/uam_alex/backend/', MEDIA_URL)
MEDIA_ROOT = os.path.join('d:/temp/', MEDIA_URL)

SAML_FOLDER = os.path.join(BASE_DIR, 'common/saml')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'common.jud_auth.JudSAMLBackend',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_STORAGE = 'spa.storage.SPAStaticFilesStorage'
